name: Build and Deploy

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0  # Replace with your desired Ruby version

      - name: Install dependencies
        run: |
          bundle install
          gem install jekyll

      - name: Build Jekyll site
        run: jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Change this to your Jekyll build output directory
